<a href="https://colab.research.google.com/github/JAYDEEPMISHR/PYTHON/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## NumPy


*   It is a most important library of python which stores the data in different form like 1-d,2-d,3-d and so on.


*  It is alibrary which are used to computation and processing of single and multi-dimensional arrays of element



In [2]:
import numpy as np

In [ ]:
a = np.array([1,2,3])
print(a)

[1 2 3]


If i check type of this a than:

In [ ]:
print(type(a))

<class 'numpy.ndarray'>


<class 'numpy.ndarray'> is numpy 'n' dimensional array

In [ ]:
a = np.array([1,2,3], dtype = float) # Apply datatype in which i want to pass the data
print(a)

[1. 2. 3.]


In [ ]:
a = np.array([1,2,3], dtype = str)
print(a)

['1' '2' '3']


In [ ]:
b = np.array([1,2,3],[4,5,6]) # 2-D array
print(b)

TypeError: Field elements must be 2- or 3-tuples, got '4'

In [ ]:
b = np.array([[1,2,3],[4,5,6]]) # 2-D array
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
print(len(b))

2


In [ ]:
print(b.ndim) # If you want to know how many dimension are there

2


In [ ]:
c = np.array([[[1, 2, 4, 5], [5, 6, 7, 8]], [["a", "b", "c", "d"], ["e", "f", "g", "h"]]], dtype=object)
print(c)

[[[1 2 4 5]
  [5 6 7 8]]

 [['a' 'b' 'c' 'd']
  ['e' 'f' 'g' 'h']]]


In [ ]:
c = np.array([[[1, 2, 4, 5], [5, 6, 7, 8]], [["a", "b", "c", "d"], ["e", "f", "g", "h"]]], dtype=object)
print(c.ndim)

3


In [ ]:
# Numpy's most important methods
# Get a shape of a numpy array means how many rows and how many coloums do you have in the array we know using this method.

print(c.shape)

(2, 2, 4)


In [ ]:
# If we want to know which data type do the array have than use "dtype"
print(c.dtype)

object


# Accessing/Changing specific Elements,rows & Coloum etc.

In [ ]:
a = np.array([[1,2,3,4], [5,12,11,14]])
print(a)

[[ 1  2  3  4]
 [ 5 12 11 14]]


In [ ]:
a.ndim

2

In [ ]:
a.shape

(2, 4)

In [ ]:
# Get a specific element from the array
print(a[0,3])

4


In [ ]:
# Get a specific row from the array
print(a[1,:])

[ 5 12 11 14]


In [ ]:
# Get a specific coloum from the array
print(a[:,3])

[ 4 14]


In [ ]:
# Change some value from the array

In [ ]:
a[1,3] = 30
print(a)

[[ 1  2  3  4]
 [ 5 12 11 30]]


# Zeros/Ones methods in Numpy

In [ ]:
e = np.zeros((3))
print(e)

[0. 0. 0.]


In [ ]:
e = np.zeros((3,5)) # This will give you the answer in the float if we want to convert this into int than put dtype = 'int32'
print(e)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
e = np.zeros((3,5), dtype = 'int32')
print(e)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [ ]:
e = np.zeros((3,5), dtype = 'int64') # same result in int64
print(e)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [ ]:
e = np.zeros((3,5), dtype = 'str') # in the string
print(e)

[['' '' '' '' '']
 ['' '' '' '' '']
 ['' '' '' '' '']]


In [ ]:
e = np.ones((3,5)) # For 1's
print(e)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
e = np.ones((3,5), dtype = "int") # For 1's
print(e)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [ ]:
e = np.ones((3,5), dtpye = "str") # For 1's
print(e)

TypeError: ones() got an unexpected keyword argument 'dtpye'

In [3]:
e = np.full((3,5), 5) # This full method to create the array which is full of only one element
print(e)

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


In [5]:
e = np.random.rand(3,5) # For Creating random numbers array in float
print(e)

[[0.95603577 0.11391235 0.30986446 0.80229311 0.6288414 ]
 [0.20768406 0.8621895  0.48718322 0.42979038 0.6383241 ]
 [0.98450665 0.41171225 0.38479784 0.96803371 0.33533657]]


In [7]:
e = np.random.randint(3,100, size = (4,5)) # For Creating random numbers array in int "randint(range, size of an array)
print(e)

[[69 54 33 99 18]
 [92 24 62 19 53]
 [25 68 63 70 42]
 [38 94 38 65 31]]


In [11]:
e = np.identity(5) # Creat an identity metrix
print(e)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [12]:
e = np.identity(5, dtype = "int") # Creat an identity metrix
print(e)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
