<a href="https://colab.research.google.com/github/JAYDEEPMISHR/PYTHON/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## NumPy


*   It is a most important library of python which stores the data in different form like 1-d,2-d,3-d and so on.


*  It is alibrary which are used to computation and processing of single and multi-dimensional arrays of element



In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])
print(a)

[1 2 3]


If i check type of this a than:

In [3]:
print(type(a))

<class 'numpy.ndarray'>


<class 'numpy.ndarray'> is numpy 'n' dimensional array

In [4]:
a = np.array([1,2,3], dtype = float) # Apply datatype in which i want to pass the data
print(a)

[1. 2. 3.]


In [5]:
a = np.array([1,2,3], dtype = str)
print(a)

['1' '2' '3']


In [6]:
b = np.array([1,2,3],[4,5,6]) # 2-D array
print(b)

TypeError: Field elements must be 2- or 3-tuples, got '4'

In [7]:
b = np.array([[1,2,3],[4,5,6]]) # 2-D array
print(b)

[[1 2 3]
 [4 5 6]]


In [8]:
print(len(b))

2
